version: '3.8'

services:
  backend:
    image: aleksandrovyur11/internet_newspaper:backend
    container_name: backend
    depends_on:
      - psql-db
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/Internet-newspaper
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgre

  frontend:
    image: aleksandrovyur11/internet_newspaper:frontend
    container_name: frontend
    ports:
      - "5173:5173"

  psql-db:
    image: postgres:latest
    container_name: psql-db
    environment:
      - POSTGRES_DB=Internet-newspaper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql