CREATE EXTENSION pgcrypto;
SET TIME ZONE 'Europe/Moscow';

-- Создание таблиц
CREATE TABLE IF NOT EXISTS theme
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS role
(
    name VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS picture
(
    id  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "user"
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) CHECK (LENGTH(name) >= 2),
    surname VARCHAR(255) CHECK (LENGTH(surname) >= 2),
    email     VARCHAR(255) UNIQUE,
    role_name VARCHAR(255) REFERENCES role (name) ON DELETE CASCADE,
    password  VARCHAR(255) CHECK (password ~ '^(?=.*[0-9])(?=.*[a-zA-Z]).{8,}$')
);

CREATE TABLE IF NOT EXISTS news
(
    id                  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    news_title          VARCHAR(255) NOT NULL,
    news_text           TEXT         NOT NULL,
    date_published_news TIMESTAMP    NOT NULL,
    picture_id          INTEGER REFERENCES picture (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS news_theme
(
    news_id  INT REFERENCES news (id) ON DELETE CASCADE,
    theme_id INT REFERENCES theme (id) ON DELETE CASCADE,
    PRIMARY KEY (news_id, theme_id)
);

CREATE TABLE IF NOT EXISTS comment
(
    id                     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_published_comment TIMESTAMP NOT NULL,
    text_comment           varchar(1000),
    author_id              INT REFERENCES "user" (id) ON DELETE CASCADE,
    news_id                INT REFERENCES news (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "like"
(
    id      INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT,
    news_id INT,
    FOREIGN KEY (user_id) REFERENCES "user" (id),
    FOREIGN KEY (news_id) REFERENCES news (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS refresh_token
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     INT REFERENCES "user" (id),
    token       VARCHAR(255) UNIQUE NOT NULL,
    expiry_date TIMESTAMP           NOT NULL
);

-- Вставка тем
INSERT INTO theme (name)
VALUES ('GTA 6'),
       ('Игры'),
       ('Зенит'),
       ('РПЛ'),
       ('Футбол'),
       ('Погода'),
       ('Краснодар'),
       ('Sony');

-- Вставка ролей
INSERT INTO role (name)
VALUES ('ROLE_USER'),
       ('ROLE_ADMIN');

-- Вставка изображений
INSERT INTO picture (url)
VALUES ('https://img.championat.com/s/1350x900/news/big/x/k/zenit-luchshaya-komanda-rpl-.jpg'),
       ('https://ratatum.com/wp-content/uploads/2017/12/d913028356dcf7df9c5d4b13b3a9beca.jpg'),
       ('https://papik.pro/grafic/uploads/posts/2023-04/1681574046_papik-pro-p-logotip-rpl-vektor-41.jpg'),
       ('https://overclockers.ru/st/r/800/-/legacy/blog/427695/453645_O.png'),
       ('https://ss.sport-express.ru/userfiles/materials/196/1961328/volga.jpg');

-- Вставка пользователей
INSERT INTO "user" (email, name, surname, password, role_name)
VALUES ('sokolova@yandex.ru', 'Александра', 'Соколова', crypt('Sokolova92', gen_salt('bf')), 'ROLE_USER'),
       ('denisov@yandex.ru', 'Максим', 'Денисов', crypt('Denisov198', gen_salt('bf')), 'ROLE_USER'),
       ('aleksandrov@yandex.ru', 'Юрий', 'Александров', crypt('Aleksandrov47', gen_salt('bf')), 'ROLE_ADMIN');

-- Вставка новостей
INSERT INTO news (date_published_news, news_title, news_text, picture_id)
VALUES (NOW() - INTERVAL '5 minutes', 'Вышел первый трейлер GTA VI — одной из самых ожидаемых игр последних лет', 'На консолях в новую GTA можно будет сыграть не раньше весны 2025-го. Пользователям PC придется ждать еще дольше
Трейлер, в котором звучит песня «Love Is a Long Road» американского рокера Тома Петти, длится всего полторы минуты. На момент публикации этого материала ролик собрал на ютьюбе почти 70 миллионов просмотров и больше семи миллионов лайков.
Rockstar Games Grand Theft Auto VI поступит в продажу в 2025 году. Точную дату создатели пока не называют, но ранее в одном из финансовых отчетов издательство Take-Two Interactive (ему принадлежит студия Rockstar Games, работающая над GTA) обещало выпустить несколько «прорывных проектов» до 31 марта 2025 года. Что это за проекты — неизвестно, но можно предположить, что GTA VI среди них. В официальном пресс-релизе уточняется, что игра выйдет на консолях PlayStation 5 и Xbox Series X|S. Релиз на PC, скорее всего, состоится значительно позже: предыдущую часть серии пришлось ждать полтора года.
Переведут ли игру на русский язык — достоверно неизвестно. Вместе с тем в трейлере можно включить русские субтитры, а на официальном сайте Rockstar Games появилась русскоязычная страница c роликом.',
        (SELECT id FROM picture WHERE url = 'https://ss.sport-express.ru/userfiles/materials/196/1961328/volga.jpg'));

INSERT INTO news (date_published_news, news_title, news_text, picture_id)
VALUES (NOW() - INTERVAL '10 minutes', '«Зенит» — лучшая команда РПЛ после 18 туров по двум защитным метрикам', 'Пресс-служба Российской Премьер-Лиги представила отчёт по первой части сезона-2023/2024 чемпионата, в котором представлены различные статистические показатели.
Исходя из данных в отчёте, санкт-петербургский «Зенит» является лучшей командой РПЛ сразу по двум защитным метрикам. Подопечные Сергея Семака лидируют по проценту выигранных единоборств (53%), а также по проценту успешных отборов (68%).
Напомним, на данный момент после 18 сыгранных матчей РПЛ «Краснодар» под руководством Владимира Ивича располагается на первой строчке с 38 очками. На втором месте в турнирной таблице находится санкт-петербургский «Зенит». Сине-бело-голубые набрали 36 очков. На третьей строчке находится московское «Динамо» с 32 очками.',
        (SELECT id FROM picture WHERE url = 'https://img.championat.com/s/1350x900/news/big/x/k/zenit-luchshaya-komanda-rpl-.jpg'));

INSERT INTO news (date_published_news, news_title, news_text, picture_id)
VALUES (NOW() - INTERVAL '15 minutes', 'В Петербурге побит рекорд по самой низкой температуре в истории города', 'Сразу три рекорда - по ночной, дневной и среднесуточной температуре - были побиты в Петербурге 4 января 2024 года, эти сутки стали самыми холодными за весь период инструментальных наблюдений в городе. Об этом сообщил главный синоптик Петербурга Александр Колесов.
"В Санкт-Петербурге снова перекрыты три рекорда температуры - ночной, дневной и среднесуточной. Получается, что сутки 4 января этого года вообще самые холодные в истории города, а отклонение температуры воздуха от нормы вчера составило 19,5 градуса", - написал он в Telegram-канале.
Колесов добавил, что дневная температура в Санкт-Петербурге стала самой низкой за весь ряд инструментальных наблюдений. Днем 4 января температура в городе не превысила -22,1 градуса, прошлый рекорд -18,1 градуса повторялся в этот день два раза: в 1985 и 2003 годах. Среднесуточная температура перекрыла предыдущий рекорд все того же 1950 года, когда 4 января в Ленинграде было -22,1 градуса. Вчера в городе среднесуточная температура понизилась до -23,6 градуса, теперь это самые морозные сутки в истории города для 4 января.
По словам синоптика, 5 января рекордов уже не ожидается. Самая низкая температура в этот день была зафиксирована в 1950 году -28,9 градуса.',
        (SELECT id FROM picture WHERE url = 'https://ratatum.com/wp-content/uploads/2017/12/d913028356dcf7df9c5d4b13b3a9beca.jpg'));

INSERT INTO news (date_published_news, news_title, news_text, picture_id)
VALUES (NOW() - INTERVAL '18 minutes', 'Гонка «Зенита» и «Краснодара»: краснодарцы снова приблизились', 'В таблице «Краснодар» выше «Зенита», а в сравнении коэффициентов на титул пока только стремится догнать.
Команда Владимира Ивича впервые приблизилась после седьмого тура – когда оторвалась ото всех соперников хотя бы на три очка. «Зенит» тогда был вторым, но шел вровень с «Крыльями» и «Динамо», выбравшись из последствий неудачного старта.
Коэффициенты на чемпионство в РПЛ обновляются не каждый тур – вот график сближения, небольшого удаления и снова сближения за лето, осень и начало зимы. 4.50 – коэффициент перед выездом краснодарцев в Петербург, в том матчи они были андердогами. Но не проиграли и хоть следом на неделю упустили лидерство, в декабре все же вернулись на первое место, а соответственно приблизились и к чемпионству и по оценкам букмекеров тоже.',
        (SELECT id FROM picture WHERE url = 'https://papik.pro/grafic/uploads/posts/2023-04/1681574046_papik-pro-p-logotip-rpl-vektor-41.jpg'));

INSERT INTO news (date_published_news, news_title, news_text, picture_id)
VALUES (NOW() - INTERVAL '25 minutes','Взлом Insomniac Games стал серьезным ударом по репутации Sony', 'Группа Rhysida ransomware взломала компанию Insomniac Games, принадлежащую Sony, и украла 1,67 терабайта данных, включая частную информацию и планы игр. Хакеры из группы Rhysida ransomware опубликовали 1,3 миллиона файлов данных от компании Insomniac Games, принадлежащей Sony. Этот инцидент стал неблагоприятным событием для репутации компании в индустрии.
Общий объем данных составил 1,67 терабайта и, по предположениям, включает в себя частную информацию о сотрудниках, внутренние письма, банковские данные, номера кредитных карт, а также файлы о персонале и руководителях компании. Кроме того, злоумышленники похитили планы игр, бюджеты и информацию о предстоящих проектах.
Эрфан Шадаби, эксперт по кибербезопасности в Comforte AG, подчеркнул, что такая информация может быть весьма полезной для конкурентов и нанести серьезный урон операционной деятельности Sony.
Группа Rhysida ransomware уже угрожала продать украденные данные на аукционе по цене в 50 биткоинов, что эквивалентно более чем $2 миллионам. Несколько данных было опубликовано на темном веб-сайте после закрытия аукциона.
Это уже вторая значительная атака группы Rhysida за последние три месяца. Группа также подозревается в кибератаке на Британскую библиотеку.',
        (SELECT id FROM picture WHERE url = 'https://overclockers.ru/st/r/800/-/legacy/blog/427695/453645_O.png'));

-- Присвоение тем для новостей
INSERT INTO news_theme (news_id, theme_id) VALUES (1, 1);
INSERT INTO news_theme (news_id, theme_id) VALUES (1, 2);
INSERT INTO news_theme (news_id, theme_id) VALUES (2, 3);
INSERT INTO news_theme (news_id, theme_id) VALUES (2, 4);
INSERT INTO news_theme (news_id, theme_id) VALUES (2, 5);
INSERT INTO news_theme (news_id, theme_id) VALUES (3, 6);
INSERT INTO news_theme (news_id, theme_id) VALUES (4, 7);
INSERT INTO news_theme (news_id, theme_id) VALUES (4, 3);
INSERT INTO news_theme (news_id, theme_id) VALUES (4, 4);
INSERT INTO news_theme (news_id, theme_id) VALUES (4, 5);
INSERT INTO news_theme (news_id, theme_id) VALUES (5, 8);
INSERT INTO news_theme (news_id, theme_id) VALUES (5, 2);

-- Вставка комментариев
INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '1 minutes', 'Сколько будет стоить дисковая версия?',
        (SELECT id FROM "user" WHERE email = 'aleksandrov@yandex.ru'),
        (SELECT id FROM news WHERE news_title = 'Вышел первый трейлер GTA VI — одной из самых ожидаемых игр последних лет'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '1 minutes', 'Я ждала этого 11 лет',
        (SELECT id FROM "user" WHERE email = 'sokolova@yandex.ru'),
        (SELECT id FROM news WHERE news_title = 'Вышел первый трейлер GTA VI — одной из самых ожидаемых игр последних лет'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '2 minutes', 'А про что сюжет будет?',
        (SELECT id FROM "user" WHERE email = 'sokolova@yandex.ru'),
        (SELECT id FROM news WHERE news_title = 'Вышел первый трейлер GTA VI — одной из самых ожидаемых игр последних лет'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '3 minutes', 'Когда выйдет на ПК?',
        (SELECT id FROM "user" WHERE email = 'denisov@yandex.ru'),
        (SELECT id FROM news WHERE news_title = 'Вышел первый трейлер GTA VI — одной из самых ожидаемых игр последних лет'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '6 minutes', 'Ничего неонятно, но очень интересно',
        (SELECT id FROM "user" WHERE email = 'sokolova@yandex.ru'),
        (SELECT id FROM news WHERE news_title = '«Зенит» — лучшая команда РПЛ после 18 туров по двум защитным метрикам'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '7 minutes', 'Верните Халка и Витселя!!!',
        (SELECT id FROM "user" WHERE email = 'denisov@yandex.ru'),
        (SELECT id FROM news WHERE news_title = '«Зенит» — лучшая команда РПЛ после 18 туров по двум защитным метрикам'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '10 minutes', 'Все праздники из-за мороза просидела дома(',
        (SELECT id FROM "user" WHERE email = 'sokolova@yandex.ru'),
        (SELECT id FROM news WHERE news_title = 'В Петербурге побит рекорд по самой низкой температуре в истории города'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '5 minutes', 'Все каникулы проболел',
        (SELECT id FROM "user" WHERE email = 'aleksandrov@yandex.ru'),
        (SELECT id FROM news WHERE news_title = 'В Петербурге побит рекорд по самой низкой температуре в истории города'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '11 minutes', 'Вот бы каждый год были такие морозы)',
        (SELECT id FROM "user" WHERE email = 'denisov@yandex.ru'),
        (SELECT id FROM news WHERE news_title = 'В Петербурге побит рекорд по самой низкой температуре в истории города'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '13 minutes', 'Вперед, Зенит!!!',
        (SELECT id FROM "user" WHERE email = 'sokolova@yandex.ru'),
        (SELECT id FROM news WHERE news_title = 'Гонка «Зенита» и «Краснодара»: краснодарцы снова приблизились'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '14 minutes', 'Вперед, Быки!!!',
        (SELECT id FROM "user" WHERE email = 'denisov@yandex.ru'),
        (SELECT id FROM news WHERE news_title = 'Гонка «Зенита» и «Краснодара»: краснодарцы снова приблизились'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '10 minutes', 'Жалко разработчиков, они хотели сделать сюрприз, а его теперь не будет',
        (SELECT id FROM "user" WHERE email = 'denisov@yandex.ru'),
        (SELECT id FROM news WHERE news_title = 'Взлом Insomniac Games стал серьезным ударом по репутации Sony'));

INSERT INTO comment (date_published_comment, text_comment, author_id, news_id)
VALUES (NOW() - INTERVAL '7 minutes', 'Не ожидал, что у них такая слабая система беопасности',
        (SELECT id FROM "user" WHERE email = 'denisov@yandex.ru'),
        (SELECT id FROM news WHERE news_title = 'Взлом Insomniac Games стал серьезным ударом по репутации Sony'));